<a href="https://colab.research.google.com/github/zelssz/Checkpoint-1-Avd/blob/main/Minpro2_AVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# **Data Understanding**

In [116]:
df = pd.read_csv('/content/customer_segmentation_data (1).csv')

df.head()

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08

In [ ]:
print("\nMenampilkan ringkasan informasi dataset dengan df.info():")
df.info()

Menampilkan ringkasan informasi dataset dengan df.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1000 non-null   int64
 1   age                   1000 non-null   int64
 2   gender                1000 non-null   object
 3   income                1000 non-null   int64
 4   spending_score        1000 non-null   int64
 5   membership_years      1000 non-null   int64
 6   purchase_frequency    1000 non-null   int64
 7   preferred_category    1000 non-null   object
 8   last_purchase_amount  1000 non-null   float64
dtypes: float64(1), int64(6), object(2)
memory usage: 70.4+ KB

In [ ]:
print("\nMenampilkan statistik deskriptif dengan df.describe():")
df.describe()

Menampilkan statistik deskriptif dengan df.describe():

,id,age,income,spending_score,membership_years,purchase_frequency,last_purchase_amount
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,500.500000,43.783000,88500.800000,50.685000,5.46900,26.596000,492.348670
std,288.819436,15.042213,34230.771122,28.955175,2.85573,14.243654,295.744253
min,1.000000,18.000000,30004.000000,1.000000,1.00000,1.000000,10.400000
25%,250.750000,30.000000,57911.750000,26.000000,3.00000,15.000000,218.762500
50%,500.500000,45.000000,87845.500000,50.000000,5.00000,27.000000,491.595000
75%,750.250000,57.000000,116110.250000,76.000000,8.00000,39.000000,747.170000
max,1000.000000,69.000000,149973.000000,100.000000,10.00000,50.000000,999.740000

In [ ]:
print(f"\nMenghitung jumlah kemunculan nilai unik dalam kolom  dengan df.value_counts():")
df.value_counts()

Menghitung jumlah kemunculan nilai unik dalam kolom  dengan df.value_counts():

id    age  gender  income  spending_score  membership_years  purchase_frequency  preferred_category  last_purchase_amount
1     38   Female  99342   90              3                 24                  Groceries           113.53                  1
672   30   Male    94803   76              6                 33                  Home & Garden       596.98                  1
659   35   Other   116378  38              10                11                  Clothing            79.27                   1
660   54   Female  89035   14              4                 11                  Sports              138.81                  1
661   69   Female  34122   50              4                 27                  Sports              758.44                  1
                                                                                                                            ..
339   28   Female  111697  92              9                 50                  Sports              205.58                  1
340   48   Other   30374   28              7                 34                  Groceries           463.78                  1
341   31   Other   35406   45              10                9                   Electronics         637.02                  1
342   69   Female  71688   69              4                 25                  Clothing            532.23                  1
1000  36   Female  90420   7               2                 31                  Groceries           669.26                  1
Name: count, Length: 1000, dtype: int64

In [ ]:
print("\nMenghitung korelasi antar kolom numerik dengan df.corr():")
print(df.corr(numeric_only=True))

Menghitung korelasi antar kolom numerik dengan df.corr():
                            id       age    income  spending_score  \
id                    1.000000  0.003226  0.017901       -0.025673
age                   0.003226  1.000000 -0.000688        0.017707
income                0.017901 -0.000688  1.000000        0.000020
spending_score       -0.025673  0.017707  0.000020        1.000000
membership_years     -0.009753 -0.003431 -0.035783        0.026726
purchase_frequency   -0.013006 -0.030137  0.000533        0.006708
last_purchase_amount  0.027475  0.061599 -0.054006       -0.014475

                      membership_years  purchase_frequency  \
id                           -0.009753           -0.013006
age                          -0.003431           -0.030137
income                       -0.035783            0.000533
spending_score                0.026726            0.006708
membership_years              1.000000            0.069532
purchase_frequency            0.069532            1.000000
last_purchase_amount         -0.014135            0.024400

                      last_purchase_amount
id                                0.027475
age                               0.061599
income                           -0.054006
spending_score                   -0.014475
membership_years                 -0.014135
purchase_frequency                0.024400
last_purchase_amount              1.000000

# **Data Preparation**

Missing Value

In [ ]:
print((df.isna().sum() / len(df)) * 100)

id                      0.0
age                     0.0
gender                  0.0
income                  0.0
spending_score          0.0
membership_years        0.0
purchase_frequency      0.0
preferred_category      0.0
last_purchase_amount    0.0
dtype: float64

Melakukan pengecekan nilai kosong pada kolom

In [ ]:
df[df['membership_years'].isnull()]

Empty DataFrame
Columns: [id, age, gender, income, spending_score, membership_years, purchase_frequency, preferred_category, last_purchase_amount]
Index: []

In [ ]:
df

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08
...,...,...,...,...,...,...,...,...,...
995,996,57,Male,112170,57,6,1,Clothing,313.64
996,997,23,Other,65337,76,10,23,Groceries,632.83
997,998,23,Male,113097,40,5,42,Sports,75.09
998,999,22,Female,113695,63,7,44,Electronics,505.16
999,1000,36,Female,90420,7,2,31,Groceries,669.26

Duplikat

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, age, gender, income, spending_score, membership_years, purchase_frequency, preferred_category, last_purchase_amount]
Index: []

In [ ]:
df

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08
...,...,...,...,...,...,...,...,...,...
995,996,57,Male,112170,57,6,1,Clothing,313.64
996,997,23,Other,65337,76,10,23,Groceries,632.83
997,998,23,Male,113097,40,5,42,Sports,75.09
998,999,22,Female,113695,63,7,44,Electronics,505.16
999,1000,36,Female,90420,7,2,31,Groceries,669.26

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08
...,...,...,...,...,...,...,...,...,...
995,996,57,Male,112170,57,6,1,Clothing,313.64
996,997,23,Other,65337,76,10,23,Groceries,632.83
997,998,23,Male,113097,40,5,42,Sports,75.09
998,999,22,Female,113695,63,7,44,Electronics,505.16
999,1000,36,Female,90420,7,2,31,Groceries,669.26

# **Outliers**

In [ ]:
results = []

cols = df.select_dtypes(include=['float64', 'int64'])

for col in cols:
  q1 = df[col].quantile(0.25)
  q3 = df[col].quantile(0.75)
  iqr = q3 - q1
  lower_bound = q1 - 1.5*iqr
  upper_bound = q3 + 1.5*iqr
  outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
  percent_outliers = (len(outliers)/len(df))*100
  results.append({'Kolom': col, 'Persentase Outliers': percent_outliers})

# Dataframe dari list hasil
results_df = pd.DataFrame(results)
results_df.set_index('Kolom', inplace=True)
results_df = results_df.rename_axis(None, axis=0).rename_axis('Kolom', axis=1)

# Tampilkan dataframe
display(results_df)

Kolom                 Persentase Outliers
id                                    0.0
age                                   0.0
income                                0.0
spending_score                        0.0
membership_years                      0.0
purchase_frequency                    0.0
last_purchase_amount                  0.0

Data sudah konsisten

In [ ]:
df

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08
...,...,...,...,...,...,...,...,...,...
995,996,57,Male,112170,57,6,1,Clothing,313.64
996,997,23,Other,65337,76,10,23,Groceries,632.83
997,998,23,Male,113097,40,5,42,Sports,75.09
998,999,22,Female,113695,63,7,44,Electronics,505.16
999,1000,36,Female,90420,7,2,31,Groceries,669.26

# **Construct Data**

In [117]:
df['Total Purchases'] = df['purchase_frequency'] * df['last_purchase_amount']

print(df.head())

   id  age  gender  income  spending_score  membership_years  \
0   1   38  Female   99342              90                 3
1   2   21  Female   78852              60                 2
2   3   60  Female  126573              30                 2
3   4   40   Other   47099              74                 9
4   5   65  Female  140621              21                 3

   purchase_frequency preferred_category  last_purchase_amount  \
0                  24          Groceries                113.53
1                  42             Sports                 41.93
2                  28           Clothing                424.36
3                   5      Home & Garden                991.93
4                  25        Electronics                347.08

   Total Purchases
0          2724.72
1          1761.06
2         11882.08
3          4959.65
4          8677.00

In [120]:
df

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08
...,...,...,...,...,...,...,...,...,...
995,996,57,Male,112170,57,6,1,Clothing,313.64
996,997,23,Other,65337,76,10,23,Groceries,632.83
997,998,23,Male,113097,40,5,42,Sports,75.09
998,999,22,Female,113695,63,7,44,Electronics,505.16
999,1000,36,Female,90420,7,2,31,Groceries,669.26

# **Data Reduction**

In [118]:
df = df.drop(columns=["Total Purchases"])
print(df.head())

   id  age  gender  income  spending_score  membership_years  \
0   1   38  Female   99342              90                 3
1   2   21  Female   78852              60                 2
2   3   60  Female  126573              30                 2
3   4   40   Other   47099              74                 9
4   5   65  Female  140621              21                 3

   purchase_frequency preferred_category  last_purchase_amount
0                  24          Groceries                113.53
1                  42             Sports                 41.93
2                  28           Clothing                424.36
3                   5      Home & Garden                991.93
4                  25        Electronics                347.08

In [119]:
df

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08
...,...,...,...,...,...,...,...,...,...
995,996,57,Male,112170,57,6,1,Clothing,313.64
996,997,23,Other,65337,76,10,23,Groceries,632.83
997,998,23,Male,113097,40,5,42,Sports,75.09
998,999,22,Female,113695,63,7,44,Electronics,505.16
999,1000,36,Female,90420,7,2,31,Groceries,669.26